@Library('sharelib@main') _

pipeline {
    agent {
        node {
            label 'go'
        }
    }
    parameters {
        string(name: 'BUILD_BRANCH', defaultValue: 'main', description: '请输入要的构建分支名')
        booleanParam(name: 'BUILD_CMD', defaultValue: false, description: '是否构建命令行工具')
        booleanParam(name: 'BUILD_SERVER', defaultValue: false, description: '是否构建服务端')
        booleanParam(name: 'TEST', defaultValue: false, description: '是否进行测试')
    }

    stages {
        stage('Check GO VERSION') {
            steps {
                script {
                    sh 'go version'
                }
            }
        }
        stage('Build') {
            parallel {
                stage('Build CMD') {
                    when {
                        expression {
                            return params.BUILD_CMD
                        }
                    }
                    steps {
                        script {
                            def params = [:]
                            params['BUILD_BRANCH'] = "${BUILD_BRANCH}"
                            params['OWNER'] = 'secretpot'
                            params['REPO'] = 'go-project-example'
                            params['TARGET'] = 'cmd'
                            def builder = new build.builderForGithub()
                            builder.buildGolangProject(params)
                        }
                    }
                }
                stage('BUILD SERVER') {
                    when {
                        expression {
                            return params.BUILD_SERVER
                        }
                    }
                    steps {
                        script {
                            def params = [:]
                            params['BUILD_BRANCH'] = "${BUILD_BRANCH}"
                            params['OWNER'] = 'secretpot'
                            params['REPO'] = 'go-project-example'
                            params['TARGET'] = 'server'
                            def builder = new build.builderForGithub()
                            builder.buildGolangProject(params)
                        }
                    }
                }
            }
        }
        stage('Test') {
            when {
                expression {
                    return params.TEST
                }
            }
            steps {
                script {
                    sh "scrpts/cmd_test.sh"
                    sh "scrip/server_test.sh"
                }
            }
        }
    }
}
